name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  branch:
    description: 'Current branch'
    required: true
    default: ''
  repo:
    description: 'Current repo'
    required: true
    default: ''
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node12'
  main: 'index.js'